<a href="https://colab.research.google.com/github/aniruddhha/machine-learning-practice/blob/master/first-nn-tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print('Tensorflow Version ', tf.__version__)

Tensorflow Version  2.9.2


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()


In [3]:
x_train, x_test = x_train/255.0, x_test/255.0

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.69327897, -0.5995329 , -0.5565798 , -0.47413838,  0.40045545,
        -0.14141186, -0.00677383,  0.5024449 ,  0.3949021 , -0.52066344]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.05358582, 0.05885228, 0.06143524, 0.06671469, 0.15997522,
        0.09305137, 0.10646217, 0.17715205, 0.1590893 , 0.06368188]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.3746037

In [9]:
model.compile(
    optimizer = 'adam',
    loss = loss_fn,
    metrics = ['accuracy']
)

In [10]:
model.fit(x_train, y_train, epochs = 10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2940 - accuracy: 0.9138
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1450 - accuracy: 0.9565
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1090 - accuracy: 0.9667
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0896 - accuracy: 0.9724
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0748 - accuracy: 0.9761
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0640 - accuracy: 0.9787
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0594 - accuracy: 0.9811
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0535 - accuracy: 0.9827
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0488 - accuracy: 0.9837
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.044

In [13]:
model.evaluate(x_test, y_test, verbose = 3)

[0.07238884270191193, 0.9789000153541565]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.0914193e-09, 5.2410754e-10, 8.3608754e-08, 3.7139991e-06,
        1.1983006e-14, 1.4585441e-08, 2.5648430e-16, 9.9999571e-01,
        2.3551060e-08, 4.8219027e-07],
       [1.9168042e-11, 1.9178579e-03, 9.9807692e-01, 4.3208090e-07,
        1.1079461e-19, 4.7457543e-06, 6.8384849e-09, 4.7777862e-16,
        2.8046996e-09, 2.3524756e-19],
       [1.0686531e-08, 9.9927241e-01, 2.3358769e-04, 9.9488386e-07,
        3.3713881e-05, 5.5205501e-08, 2.6169326e-07, 4.2682912e-04,
        3.2190324e-05, 4.5836419e-08],
       [9.9997771e-01, 6.7572836e-10, 2.1824831e-05, 5.5088631e-08,
        8.4598173e-10, 6.3644350e-08, 3.7816807e-07, 1.5377416e-09,
        1.4737710e-10, 6.6399499e-09],
       [1.8194986e-06, 1.1970379e-10, 5.1283087e-06, 7.5186213e-09,
        9.9694520e-01, 5.1138596e-07, 2.8205978e-08, 8.5724139e-05,
        1.8699246e-06, 2.9597809e-03]], dtype=float32)>